# This is an appspec.yml template file for use with AWS CodeDeploy.
# For help completing this file, see the "AppSpec File Reference" in the  
#   "AWS CodeDeploy User Guide" at
#   http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html

# do not change version, this is controlled by AWS
version: 0.0
os: linux 
files:
  - source: /
    destination: /var/www/html
permissions:
  - object: /var/www/html
    pattern: "*.html"
    owner: root
    group: root
    mode: 755
  - object: /var/www/html/scripts
    pattern: "*.sh"
    owner: root
    group: root
    mode: 700
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_httpd.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: scripts/validate_me.sh
      timeout: 60
      runas: root
